import 'package:flutter/material.dart';

SizedBox width20() => const SizedBox(width: 20);
SizedBox height20() => const SizedBox(height: 20);
SizedBox height10() => const SizedBox(height: 10);

const List<String> days = <String>[
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

const List<String> weatherStatus = <String>[
  'Sunny',
  'Smoky',
  'Icy',
  'Misty',
  'Dewy',
  'Frosty',
  'Hot',
  'Cold',
  'Humid',
  'Dry',
  'Wet',
  'Breezy',
  'Gusty',
  'Hurricane',
  'Tornado',
  'Thunderstorm',
  'Lightning',
  'Rainbow',
  'Aurora',
  'Hail',
  'Sleet',
  'Blizzard',
  'Drizzle',
  'Shower',
  'Downpour',
  'Monsoon',
  'Typhoon',
  'Whirlpool',
  'Tsunami',
  'Drought',
  'Heatwave',
  'Sandstorm',
  'Solar',
  'Eclipse',
  'Meteor',
  'Comet',
  'Asteroid',
  'Cloudy',
  'Rainy',
  'Snowy',
  'Windy',
  'Stormy',
  'Foggy',
  'Hazy',
  'Dusty',
  'Sandy',
];
