import 'package:flutter/material.dart';

SizedBox width20() => const SizedBox(width: 20);
SizedBox height20() => const SizedBox(height: 20);
SizedBox height10() => const SizedBox(height: 10);

const List<String> days = <String>[
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

const List<String> weatherStatusWithImage = <String>[
  'Cloud',
  'Crescent Moon',
  'Light',
  'Lightning Rain',
  'Lightning',
  'Night Rain',
  'Night Snow',
  'Night Thunderstorm',
  'Night',
  'Rain Snow Water',
  'Rain Water',
  'Rain',
  'Snow Wind',
  'Snow',
  'Snowfall',
  'Stars',
  'Sun',
  'Sunny Cloudy',
  'Sunny Lightning',
  'Sunny Rain',
  'Sunny Snow',
  'Sunny Windy',
  'Wind',
  'Windy',
];
const List<String> weatherStatus = <String>[
  'Sunny',
  'Smoky',
  'Icy',
  'Misty',
  'Dewy',
  'Frosty',
  'Hot',
  'Cold',
  'Humid',
  'Dry',
  'Wet',
  'Breezy',
  'Gusty',
  'Hurricane',
  'Tornado',
  'Thunderstorm',
  'Lightning',
  'Rainbow',
  'Aurora',
  'Hail',
  'Sleet',
  'Blizzard',
  'Drizzle',
  'Shower',
  'Downpour',
  'Monsoon',
  'Typhoon',
  'Whirlpool',
  'Tsunami',
  'Drought',
  'Heatwave',
  'Sandstorm',
  'Solar',
  'Eclipse',
  'Meteor',
  'Comet',
  'Asteroid',
  'Cloudy',
  'Rainy',
  'Snowy',
  'Windy',
  'Stormy',
  'Foggy',
  'Hazy',
  'Dusty',
  'Sandy',
];
